name: Should run reuseable workflow

on:
  workflow_call:
    inputs:
      projects:
        description: The projects to match against
        required: true
        type: string
      diff_filter:
        description: Filter to use on git diff
        required: false
        type: string
        default: d
    outputs:
      result:
        description: JSON result - One boolean property for each input project
        value: ${{ jobs.main.outputs.result }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ toJSON(steps.changes.outputs) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: env

      - name: Fetching base and head commit
        id: base
        run: |
          git init
          git remote add origin ${{ github.repository.url }}

          declare -i fetch_depth=1

          case "${{ github.event_name }}" in
          push)
            git fetch --no-tags --prune --progress --no-recurse-submodules --depth=$fetch_depth origin ${{ github.event.before }}
            git fetch --no-tags --prune --progress --no-recurse-submodules --depth=$fetch_depth origin ${{ github.event.after }}
            git checkout --progress --force ${{ github.event.after }}
            echo "::set-output name=sha::${{ github.event.before }}"
            ;;
          pull_request)
            fetch_depth=$((${{ github.event.pull_request.commits }} + 1))
            git fetch --no-tags --prune --progress --no-recurse-submodules --depth=$fetch_depth origin ${{ github.event.pull_request.head.sha }}
            git checkout --progress --force ${{ github.event.pull_request.head.sha }}
            echo "::set-output name=sha::$(git rev-parse HEAD~$((fetch_depth - 2)))"
            ;;
          *)
            echo "::error ::Unsupported event name \"${{ github.event_name }}\" - Supported values are \"push, pull_request\""
            ;;
          esac

      - name: Determining changes
        id: changes
        run: |
          shopt -s extglob

          declare -r inputs="${{ inputs.projects }}"
          declare -r projects=${inputs//+([ ,])/|}
          declare -r pattern="($projects)/.*"

          declare -r old_IFS=$IFS
          IFS="|"
          for project in $projects
          do
            echo "::set-output name=$project::false"
          done
          IFS=$old_IFS

          echo "The pattern is: $pattern"

          while read -r line
          do
            line="/$line"
            echo "Git diff: $line"
            if [[ $line =~ $pattern ]]
            then
              echo "Match found! The match was: ${BASH_REMATCH[1]}"
              echo "::set-output name=${BASH_REMATCH[1]}::true"
            fi
          done < <(git diff --name-only --diff-filter=${{ inputs.diff_filter }} ${{ steps.base.outputs.sha }} HEAD)
