name: Should run reuseable workflow

on:
  workflow_call:
    inputs:
      projects:
        description: The projects to match against
        required: true
        type: string
      diff_filter:
        description: Filter to use on git diff
        required: false
        type: string
        default: d
    outputs:
      result:
        description: JSON result - One boolean property for each input project
        value: ${{ jobs.main.outputs.result }}

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ toJSON(steps.changes.outputs) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetching base and head commit
        id: prepare
        run: |
          git init
          git remote add origin ${{ github.event.repository.git_url }}

          case "${{ github.event_name }}" in
          push)
            git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin ${{ github.event.before }} ${{ github.event.after }}

            echo "::set-output name=base::${{ github.event.before }}"
            echo "::set-output name=head::${{ github.event.after }}"
            ;;
          pull_request)
            git fetch --no-tags --prune --no-recurse-submodules --depth=$((${{ github.event.pull_request.commits }} + 1)) origin ${{ github.event.pull_request.head.sha }}
            git fetch --no-tags --prune --no-recurse-submodules --depth=10 origin ${{ github.event.pull_request.base.sha }}
            git checkout --progress --force ${{ github.event.pull_request.head.sha }}

            while [[ -n $(git rev-list shallow ^${{ github.event.pull_request.base.sha }}) ]]
            do
              git fetch --no-tags --prune --no-recurse-submodules --deepen=10 origin ${{ github.event.pull_request.base.sha }}
            done

            base=$(git rev-list ${{ github.event.pull_request.head.sha }} ^${{ github.event.pull_request.base.sha }} | tail --lines 1 | xargs -I {} git rev-parse {}~1)

            echo "::set-output name=base::$base"
            echo "::set-output name=head::${{ github.event.pull_request.head.sha }}"
            ;;
          *)
            echo "::error ::Unsupported event name \"${{ github.event_name }}\" - Supported values are \"push, pull_request\""
            ;;
          esac

      - name: Determining changes
        id: changes
        run: |
          shopt -s extglob

          declare -r inputs="${{ inputs.projects }}"
          declare -r projects=${inputs//+([ ,])/|}
          declare -r pattern="^($projects)/.*"

          declare -r old_IFS=$IFS
          IFS="|"
          for project in $projects
          do
            echo "::set-output name=$project::false"
          done
          IFS=$old_IFS

          echo "The pattern is: $pattern"

          while read -r line
          do
            echo "Git diff: $line"
            if [[ $line =~ $pattern ]]
            then
              echo "Match found! The match was: ${BASH_REMATCH[1]}"
              echo "::set-output name=${BASH_REMATCH[1]}::true"
            fi
          done < <(git diff --name-only --diff-filter=${{ inputs.diff_filter }} ${{ steps.prepare.outputs.base }} ${{ steps.prepare.outputs.head }})
